### ISSUE TITLE
error when make check

### ISSUE THREAD

**Issue by qc20000sj** [codecryptanalysis/mccl#15]
when  I make check ,there are two errors,for example
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
Should I solve the problem?
Thank you.

**Comment by cr-marcstevens** [comment]
Thanks for notifying the issue.
But it's very unclear from this snippet where the real issue lies.
Could you share `config.log` and the full `make check` output?

**Comment by qc20000sj** [comment]
Thanke you reply.
[config.log](https://github.com/user-attachments/files/16115218/config.log)
[make check.txt](https://github.com/user-attachments/files/16115220/make.check.txt)
config.log and the full make check output are there.

**Comment by cr-marcstevens** [comment]
It looks like this is an error with `test_cuda`. 
Even though the buildsystem already supports CUDA and we have a compilation check `test_cuda`,
CUDA is not actually used in mccl yet.
You can disable building with CUDA by using `./configure --without-cuda`.

**Comment by cr-marcstevens** [comment]
I'll leave this issue open, but this will probably be fixed only later.

**Comment by qc20000sj** [comment]
I have successfully compiled this program under your advice. Thank you for your recovery.
